### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Mo7mud** [mehmetgoren/feniks#41]
Hi,
I'm installing this software on Linux Mint 21.2

I get this error :
```
mohammad@mohammad-TravelMate-P253:~/Downloads/Feniks$ sudo docker compose up
WARN[0000] /home/mohammad/Downloads/Feniks/docker-compose.yml: `version` is obsolete 
[+] Running 1/0
 ✔ Container webapp-instance  Running                                                                                                                                                    0.0s 
Attaching to ffmpeg_service-instance, mngr-instance, senseai_service-instance, smcp-instance, snapshot_service-instance, webapp-instance
ffmpeg_service-instance  | Redis host: 127.0.0.1
ffmpeg_service-instance  | Redis port: 6379
ffmpeg_service-instance  | Traceback (most recent call last):
ffmpeg_service-instance  |   File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 276, in connect
ffmpeg_service-instance  |     sock = self.retry.call_with_retry(
ffmpeg_service-instance  |   File "/usr/local/lib/python3.10/dist-packages/redis/retry.py", line 46, in call_with_retry
ffmpeg_service-instance  |     return do()
ffmpeg_service-instance  |   File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 277, in <lambda>
ffmpeg_service-instance  |     lambda: self._connect(), lambda error: self.disconnect(error)
ffmpeg_service-instance  |   File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 639, in _connect
ffmpeg_service-instance  |     raise err
ffmpeg_service-instance  |   File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 627, in _connect
ffmpeg_service-instance  |     sock.connect(socket_address)
ffmpeg_service-instance  | ConnectionRefusedError: [Errno 111] Connection refused
```

This is my composer file:

```
version: '3'
services:
  mngr:
    image: gokalpgoren/mngr:v1.0.3-amd64
    container_name: mngr-instance
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Africa/Cairo
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - WEBSERVER_PORT=8072
      - MONGODB_CS=mongodb://localhost:27017
      - SENSE_AI_IMAGE=0
      - ROOT_DIR_PATHS=/home/mohammad/Downloads/Feniks/data
      - SNAPSHOT_PROC_COUNT=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - >-
        /home/mohammad/Downloads/Feniks/data:/home/mohammad/Downloads/Feniks/data
  ffmpeg_service:
    image: gokalpgoren/ffmpeg_service:v1.0.3-amd64
    container_name: ffmpeg_service-instance
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mngr
    environment:
      - TZ=Africa/Cairo
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - >-
        /home/mohammad/Downloads/Feniks/data:/home/mohammad/Downloads/Feniks/data
  snapshot_service:
    image: gokalpgoren/snapshot_service:v1.0.3-amd64
    container_name: snapshot_service-instance
    restart: unless-stopped
    network_mode: host
    depends_on:
      - ffmpeg_service
    environment:
      - TZ=Africa/Cairo
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
  senseai_service:
    image: gokalpgoren/senseai_service:v1.0.3-amd64
    container_name: senseai_service-instance
    restart: unless-stopped
    network_mode: host
    depends_on:
      - ffmpeg_service
      - snapshot_service
      - smcp
    environment:
      - TZ=Africa/Cairo
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - >-
        /home/mohammad/Downloads/Feniks/data:/home/mohammad/Downloads/Feniks/data
  smcp:
    image: gokalpgoren/smcp:v1.0.3-amd64
    container_name: smcp-instance
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mngr
    environment:
      - TZ=Africa/Cairo
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    volumes:
      - >-
        /home/mohammad/Downloads/Feniks/data:/home/mohammad/Downloads/Feniks/data
  webapp:
    image: gokalpgoren/webapp:v1.0.3-amd64
    container_name: webapp-instance
    restart: unless-stopped
    depends_on:
      - mngr
    environment:
      - TZ=Africa/Cairo
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    ports:
      - '5000:5000'
```
